LootJS.modifiers((event) => {
	event.addLootTypeModifier(LootType.CHEST).removeLoot([
		"apotheosis:augmenting_table",
		"apotheosis:simple_reforging_table",
		"apotheosis:reforging_table",
		"apotheosis:sigil_of_rebirth",
		"apotheosis:sigil_of_enhancement"
	]);
	event.addLootTypeModifier(LootType.ENTITY).removeLoot([
		"apotheosis:augmenting_table",
		"apotheosis:simple_reforging_table",
		"apotheosis:reforging_table",
		"apotheosis:sigil_of_rebirth",
		"apotheosis:sigil_of_enhancement"
	]);
	event.addLootTypeModifier(LootType.UNKNOWN).removeLoot([
		"apotheosis:augmenting_table",
		"apotheosis:simple_reforging_table",
		"apotheosis:reforging_table",
		"apotheosis:sigil_of_rebirth",
		"apotheosis:sigil_of_enhancement"
	]);
	event.addLootTypeModifier(LootType.BLOCK).removeLoot([
		"apotheosis:augmenting_table",
		"apotheosis:simple_reforging_table",
		"apotheosis:reforging_table",
		"apotheosis:sigil_of_rebirth",
		"apotheosis:sigil_of_enhancement"
	]);
	event.addLootTypeModifier(LootType.FISHING).removeLoot([
		"apotheosis:augmenting_table",
		"apotheosis:simple_reforging_table",
		"apotheosis:reforging_table",
		"apotheosis:sigil_of_rebirth",
		"apotheosis:sigil_of_enhancement"
	]);
	event.addLootTypeModifier(LootType.GIFT).removeLoot([
		"apotheosis:augmenting_table",
		"apotheosis:simple_reforging_table",
		"apotheosis:reforging_table",
		"apotheosis:sigil_of_rebirth",
		"apotheosis:sigil_of_enhancement"
	]);
});